version: '3.8'

services:
  web:
    image: sit737-web-app:latest
    ports:
      - "3000:3000"
    restart: on-failure
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
